### ISSUE TITLE
Extend HeaderAuthentication

### ISSUE THREAD

**Issue by loju** [MikeWooster/api-client#31]
Some APis require more than one pair in header for authentication. 
Would be nice, to provide more than one pair key value, eg: get them from dict.

**Comment by MikeWooster** [comment]
That's a fantastic idea.  feel free to create a pull request for it.  My only requirement is that we don't break backwards compatibility with the existing implementation.

**Comment by loju** [comment]
Cool, one obstacle - I have no access to create dev branch.

**Comment by MikeWooster** [comment]
This might help you.
https://help.github.com/en/enterprise/2.16/user/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by MikeWooster** [comment]
I made a quick fix to this.  take a look at the rc version for 1.2.
https://pypi.org/project/api-client/1.2.0rc1/

**Comment by MikeWooster** [comment]
I have released v1.2.0. Hopefully this is flexible enough for your requirements.
