### ISSUE TITLE
Need MORE Content-type class IN request_formatter.py 

### ISSUE THREAD

**Issue by o1dcat** [MikeWooster/api-client#50]
Content-type: application/json OR NONE in request_formatter.py but need other Content-type such as Content-Type: application/x-www-form-urlencoded,  Content-Type: text/xml, Content-Type: multipart/form-data

example header:

Host: 10.10.32.13:8222
User-Agent: python-requests/2.20.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
apiKey: XXXXXXXXXXXXXXXXXXXXXXXXX
Content-type: application/x-www-form-urlencoded
Content-Length: 130

**Comment by MikeWooster** [comment]
I created the library with extensions in mind.  You can always write a new request formatter that conforms to the interface defined in the `BaseRequestFormatter`, create a PR for this project, or even ship it as a separate library i.e. `api-client-form-data`.

**Comment by MikeWooster** [comment]
closing this due to inactivitty.
